codigo-fonte/Controllers/MaterialController.cs
using Microsoft.AspNetCore.Mvc;
using PUConstruir.Filters;
using PUConstruir.Helper;
using PUConstruir.Models;
using PUConstruir.Repositorio;

namespace PUConstruir.Controllers
{
    [UsuarioLogado]
    public class MaterialController : Controller
    {
        private readonly IMaterialRepositorio _materialRepositorio;
        
        private readonly ISessao _sessao;

        public MaterialController(IMaterialRepositorio materialRepositorio, ISessao sessao)
        {
            _materialRepositorio = materialRepositorio;
            _sessao = sessao;
        }

        public IActionResult Index()
        {
            UsuarioModel usuarioLogado =  _sessao.BuscarSessaoUsuario();

            List<MaterialModel> materiais = _materialRepositorio.BuscarTodos(usuarioLogado.Id);
            
            return View(materiais);
        }

        public IActionResult Criar()
        {
            return View();
        }

        public IActionResult Visualizar(int id)
        {
            MaterialModel material = _materialRepositorio.BuscarPorId(id);

            return View(material);
        }

        public IActionResult Editar(int id) 
        {
            MaterialModel material = _materialRepositorio.BuscarPorId(id);
         
            return View(material);
        }

        public IActionResult Deletar(int id)
        {
            MaterialModel material = _materialRepositorio.BuscarPorId(id);

            return View(material);
        }

        public IActionResult ConfirmarDeletar(int id)
        {

            _materialRepositorio.Apagar(id);
             
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Criar(MaterialModel material)
        {
            UsuarioModel usuarioLogado = _sessao.BuscarSessaoUsuario();
            material.UsuarioId = usuarioLogado.Id;
            _materialRepositorio.Adicionar(material);
            TempData["MensagemSucesso"] = "Material cadastrado com sucesso!";
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Alterar(MaterialModel material)
        {
            UsuarioModel usuarioLogado = _sessao.BuscarSessaoUsuario();
            material.UsuarioId = usuarioLogado.Id;
            _materialRepositorio.Atualizar(material);
            TempData["MensagemSucesso"] = "Material editado com sucesso!";
            return RedirectToAction("Index");
        }
    }
}

codigo-fonte/Views/Material/Criar.cshtml
@model MaterialModel;

@{
    ViewBag.Title = "Criar";
}

<div>
    <div>
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Criar Material</h1>
            </div>

            <form asp-controller="Material" asp-action="Criar" method="post">
                <div class="modal-body">

                    <div data-mdb-input-init>
                        <label for="descricao">Descrição:</label>
                        @Html.ValidationMessageFor(x => x.Descricao)
                        <input type="text" maxlength="120" class="form-outline mb-4 form-control form-control-lg form-projeto" id="descricao" placeholder="Descrição do Material" asp-for="Descricao">
                    </div>

                    <div data-mdb-input-init>
                        <label for="altura">Quantidade:</label>
                        <input type="number" maxlength="18" min="0" step="0.01" class="form-outline mb-4 form-control form-control-lg form-projeto" id="quantidade" placeholder="Quantidade do Material" asp-for="Quantidade">
                    </div>

                    <div data-mdb-input-init>
                        <label for="valorPadrao">Valor da Unidade:</label>
                        @Html.ValidationMessageFor(x => x.ValorPadrao)
                        <input type="number" maxlength="18" min="0" step="0.01" class="form-outline mb-4 form-control form-control-lg form-projeto" id="valorPadrao" placeholder="Preço da Unidade do Material" asp-for="ValorPadrao">
                    </div>

                    <div data-mdb-input-init>
                        <label for="um">Unidade de Medida:</label>
                        @Html.ValidationMessageFor(x => x.Um)
                        <input type="text" maxlength="10" class="form-outline mb-4 form-control form-control-lg form-projeto" id="um" placeholder="Unidade de Medida do Material" asp-for="Um">
                    </div>

                    <div data-mdb-input-init>
                        <label for="altura">Altura:</label>
                        <input type="number" maxlength="18" min="0" step="0.01" class="form-outline mb-4 form-control form-control-lg form-projeto" id="altura" placeholder="Altura do Material" asp-for="Altura">
                    </div>

                    <div data-mdb-input-init>
                        <label for="largura">Largura:</label>
                        <input type="number" maxlength="18" min="0" step="0.01" class="form-outline mb-4 form-control form-control-lg form-projeto" id="largura" placeholder="Largura do Material" asp-for="Largura">
                    </div>

                    <div data-mdb-input-init>
                        <label for="comprimento">Comprimento:</label>
                        <input type="number" maxlength="18" min="0" step="0.01" class="form-outline mb-4 form-control form-control-lg form-projeto" id="comprimento" placeholder="Comprimento do Material" asp-for="Comprimento">
                    </div>

                    <div data-mdb-input-init>
                        <label for="peso">Peso:</label>
                        <input type="number" maxlength="18" min="0" step="0.01" class="form-outline mb-4 form-control form-control-lg form-projeto" id="peso" placeholder="Peso do Material" asp-for="Peso">
                    </div>

                    <div data-mdb-input-init>
                        <label for="cor">Cor:</label>
                        <input type="text" maxlength="20" class="form-outline mb-4 form-control form-control-lg form-projeto" id="cor" placeholder="Cor do Material" asp-for="Cor">
                    </div>
                </div>

                <div class="modal-footer">
                    <a asp-controller="Material" asp-action="Index" class="btn btn-secondary">Cancelar</a>
                    <button type="submit" class="btn btn-primary">Criar</button>
                </div>
            </form>
        </div>
    </div>
</div>

codigo-fonte/Views/Material/Deletar.cshtml
@model MaterialModel;

@{
    ViewBag.Title = "Deletar";
}


<div class="centralizarTela mt-5">
    <div class="telaDeletar modal-content">
        <div class="modal-header">
            <h4 class="modal-title" id="exampleModalLabel">Excluir material</h4>
        </div>
        <div class="modal-body text-start">
            <p>
                Você está prestes a excluir o material <strong>@Model.Descricao</strong>.<br>
                Esta é uma ação definitiva, sem possibilidade de reversão.<br><br>
                Tem certeza que deseja prosseguir?
            </p>
        </div>
        <div class="modal-footer">
            <a asp-controller="Material" asp-action="Index" role="button" class="btn btn-secondary">Cancelar</a>
            <a type="button" asp-route-id="@Model.Id" asp-controller="Material" asp-action="ConfirmarDeletar" class="btn btn-danger">Excluir</a>
        </div>
    </div>
</div>

codigo-fonte/Views/Material/Editar.cshtml
@model MaterialModel;

@{
    ViewBag.Title = "Editar";
}

<div>
    <div>
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Editar Material</h1>
            </div>
            
            <form asp-controller="Material" asp-action="Alterar" method="post">
                <div class="modal-body">
                    
                    <input type="hidden" asp-for="Id">

                    <div data-mdb-input-init>
                        <label for="descricao">Descrição:</label>
                        @Html.ValidationMessageFor(x => x.Descricao)
                        <input type="text" maxlength="120" class="form-outline mb-4 form-control form-control-lg form-projeto" id="descricao" placeholder="Descrição do Material" asp-for="Descricao">
                    </div>

                    <div data-mdb-input-init>
                        <label for="valorPadrao">Valor da Unidade:</label>
                        @Html.ValidationMessageFor(x => x.ValorPadrao)
                        <input type="number" maxlength="18" min="0" step="0.01" class="form-outline mb-4 form-control form-control-lg form-projeto" id="valorPadrao" placeholder="Preço da Unidade do Material" asp-for="ValorPadrao">
                    </div>

                    <div data-mdb-input-init>
                        <label for="altura">Quantidade:</label>
                        <input type="number" maxlength="18" min="0" step="0.01" class="form-outline mb-4 form-control form-control-lg form-projeto" id="quantidade" placeholder="Quantidade do Material" asp-for="Quantidade">
                    </div>

                    <div data-mdb-input-init>
                        <label for="um">Unidade de Medida:</label>
                        @Html.ValidationMessageFor(x => x.Um)
                        <input type="text" maxlength="10" class="form-outline mb-4 form-control form-control-lg form-projeto" id="um" placeholder="Unidade de Medida do Material" asp-for="Um">
                    </div>

                    <div data-mdb-input-init>
                        <label for="altura">Altura:</label>
                        <input type="number" maxlength="18" min="0" step="0.01" class="form-outline mb-4 form-control form-control-lg form-projeto" id="altura" placeholder="Altura do Material" asp-for="Altura">
                    </div>

                    <div data-mdb-input-init>
                        <label for="largura">Largura:</label>
                        <input type="number" maxlength="18" min="0" step="0.01" class="form-outline mb-4 form-control form-control-lg form-projeto" id="largura" placeholder="Largura do Material" asp-for="Largura">
                    </div>

                    <div data-mdb-input-init>
                        <label for="comprimento">Comprimento:</label>
                        <input type="number" maxlength="18" min="0" step="0.01" class="form-outline mb-4 form-control form-control-lg form-projeto" id="comprimento" placeholder="Comprimento do Material" asp-for="Comprimento">
                    </div>

                    <div data-mdb-input-init>
                        <label for="peso">Peso:</label>
                        <input type="number" maxlength="18" min="0" step="0.01" class="form-outline mb-4 form-control form-control-lg form-projeto" id="peso" placeholder="Peso do Material" asp-for="Peso">
                    </div>

                    <div data-mdb-input-init>
                        <label for="cor">Cor:</label>
                        <input type="text" maxlength="20" class="form-outline mb-4 form-control form-control-lg form-projeto" id="cor" placeholder="Cor do Material" asp-for="Cor">
                    </div>
                </div>
                
                <div class="modal-footer">
                    <a asp-area="" asp-controller="Material" asp-action="Index" class="btn btn-secondary">Cancelar</a>
                    <button type="submit" class="btn btn-primary">Editar</button>
                </div>
            </form>
        </div>
    </div>
</div>

codigo-fonte/Views/Material/Index.cshtml
@model List<MaterialModel>;

@{
    ViewData["Title"] = "Material";
}


<div id="ProjetosTitulo">
    <h1>@ViewData["Title"]</h1>
    <a asp-area="" asp-controller="Material" asp-action="Criar" class="btn btn-dark btn-lg btn-block">
        Adicionar material +
    </a>
</div>

@if (TempData["MensagemSucesso"] != null)
{
    <div class="alert alert-success" role="alert">
        <button type="button" class="btn btn-danger btn-sm close-alert" aria-label="Close">X</button>
        @TempData["MensagemSucesso"]
    </div>
}

@if (TempData["MensagemErro"] != null)
{
    <div class="alert alert-danger" role="alert">
        <button type="button" class="btn btn-danger btn-sm close-alert" aria-label="Close">X</button>
        @TempData["MensagemErro"]
    </div>
}

@if(Model != null && Model.Any())
{
    foreach (MaterialModel material in Model)
    {
        <div id="listaStl">
            <div class="NomeDoProjeto">
                <h5>@material.Descricao</h5>
            </div>
            <div class="BotaoLateral">
                <a asp-area="" asp-controller="Material" asp-action="Visualizar" type="button" class="btn btn-lg btn-block btnCrud" asp-route-id="@material.Id">
                    <i class="fa-solid fa-magnifying-glass"></i>
                </a>

                <a asp-area="" asp-controller="Material" asp-action="Editar" type="button" class="btn btn-lg btn-block btnCrud" asp-route-id="@material.Id">
                    <i class="fa-solid fa-pencil"></i>
                </a>

                <a asp-area="" asp-controller="Material" asp-action="Deletar" type="button" class="btn btn-lg btn-block btnCrud" asp-route-id="@material.Id">
                        <i class="fa-solid fa-trash-can"></i>
                </a>
            </div>
        </div>
    }
}

codigo-fonte/Views/Material/Visualizar.cshtml
@model MaterialModel

@{
    ViewBag.Title = "Visualizar";
}

<div>
    <div> 
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Visualizar material</h1>
            </div>
            <div class="modal-body">

                <div data-mdb-input-init>
                    <label for="descricao">Descrição:</label>
                    <input type="text" readonly maxlength="120" class="form-outline mb-4 form-control form-control-lg form-projeto" id="descricao" placeholder="Descrição do Material" asp-for="Descricao">
                </div>

                <div data-mdb-input-init>
                    <label for="valorPadrao">Valor da Unidade:</label>
                    <input type="number" readonly maxlength="18" min="0" step="0.01" class="form-outline mb-4 form-control form-control-lg form-projeto" id="valorPadrao" placeholder="Preço da Unidade do Material" asp-for="ValorPadrao">
                </div>

                <div data-mdb-input-init>
                    <label for="altura">Quantidade:</label>
                    <input type="number" readonly maxlength="18" min="0" step="0.01" class="form-outline mb-4 form-control form-control-lg form-projeto" id="quantidade" placeholder="Quantidade do Material" asp-for="Quantidade">
                </div>

                <div data-mdb-input-init>
                    <label for="um">Unidade de Medida:</label>
                    <input type="text" readonly maxlength="10" class="form-outline mb-4 form-control form-control-lg form-projeto" id="um" placeholder="Unidade de Medida do Material" asp-for="Um">
                </div>

                <div data-mdb-input-init>
                    <label for="altura">Altura:</label>
                    <input type="number" readonly maxlength="18" min="0" step="0.01" class="form-outline mb-4 form-control form-control-lg form-projeto" id="altura" placeholder="Altura do Material" asp-for="Altura">
                </div>

                <div data-mdb-input-init>
                    <label for="largura">Largura:</label>
                    <input type="number" readonly maxlength="18" min="0" step="0.01" class="form-outline mb-4 form-control form-control-lg form-projeto" id="largura" placeholder="Largura do Material" asp-for="Largura">
                </div>

                <div data-mdb-input-init>
                    <label for="comprimento">Comprimento:</label>
                    <input type="number" readonly maxlength="18" min="0" step="0.01" class="form-outline mb-4 form-control form-control-lg form-projeto" id="comprimento" placeholder="Comprimento do Material" asp-for="Comprimento">
                </div>

                <div data-mdb-input-init>
                    <label for="peso">Peso:</label>
                    <input type="number" readonly maxlength="18" min="0" step="0.01" class="form-outline mb-4 form-control form-control-lg form-projeto" id="peso" placeholder="Peso do Material" asp-for="Peso">
                </div>

                <div data-mdb-input-init>
                    <label for="cor">Cor:</label>
                    <input type="text" readonly maxlength="20" class="form-outline mb-4 form-control form-control-lg form-projeto" id="cor" placeholder="Cor do Material" asp-for="Cor">
                </div>
            </div>

            <div class="modal-footer">
                <a asp-area="" asp-controller="Material" asp-action="Index" class="btn btn-secondary">Voltar</a>
            </div>
        </div>
    </div>
</div>