codigo-fonte/ViewModels/OrcamentoViewModel.cs
using PUConstruir.Models;

namespace PUConstruir.ViewModels
{
    public class OrcamentoViewModel
    {
        public OrcamentoModel Orcamento { get; set; }
        public List<ProjetoModel> TodosProjetos { get; set; }
        public List<int> ProjetosSelecionados { get; set; } = new List<int>();
    }
}

codigo-fonte/Controllers/OrcamentoController.cs
using Microsoft.AspNetCore.Mvc;
using PUConstruir.Filters;
using PUConstruir.Helper;
using PUConstruir.Models;
using PUConstruir.Repositorio;
using PUConstruir.ViewModels;
using iTextSharp.text.pdf;
using iTextSharp.text;
using Microsoft.AspNetCore.Routing;
using PUConstruir.Services;

namespace PUConstruir.Controllers
{
    [UsuarioLogado]
    public class OrcamentoController : Controller
    {
        private readonly IOrcamentoRepositorio _orcamentoRepositorio;
        private readonly IProjetoRepositorio _projetoRepositorio;
        private readonly ISessao _sessao;
        private readonly IOrcamentoService _orcamentoService;

        public OrcamentoController(IOrcamentoRepositorio orcamentoRepositorio, ISessao sessao, IProjetoRepositorio projetoRepositorio, IOrcamentoService orcamentoService)
        {
            _orcamentoRepositorio = orcamentoRepositorio;
            _projetoRepositorio = projetoRepositorio;
            _sessao = sessao;
            _orcamentoService = orcamentoService;
        }

        public IActionResult Index()
        {
            UsuarioModel usuarioLogado = _sessao.BuscarSessaoUsuario();
            List<OrcamentoModel> orcamentos = _orcamentoRepositorio.BuscarTodos(usuarioLogado.Id);
            return View(orcamentos);
        }

        public IActionResult Criar()
        {
            UsuarioModel usuarioLogado = _sessao.BuscarSessaoUsuario();
            var viewModel = new OrcamentoViewModel
            {
                TodosProjetos = _projetoRepositorio.BuscarTodos(usuarioLogado.Id)
            };
            return View(viewModel);
        }

        public IActionResult Visualizar(int id)
        {
            OrcamentoModel orcamento = _orcamentoRepositorio.BuscarPorId(id);
            return View(orcamento);
        }

        public IActionResult Editar(int id)
        {
            UsuarioModel usuarioLogado = _sessao.BuscarSessaoUsuario();
            OrcamentoModel orcamento = _orcamentoRepositorio.BuscarPorId(id);
            var viewModel = new OrcamentoViewModel
            {
                Orcamento = orcamento,
                TodosProjetos = _projetoRepositorio.BuscarTodos(usuarioLogado.Id),
                ProjetosSelecionados = orcamento.Projetos.Select(m => m.Id).ToList(),
            };
            return View(viewModel);

        }

        public IActionResult Deletar(int id)
        {
            OrcamentoModel orcamento = _orcamentoRepositorio.BuscarPorId(id);
            return View(orcamento);
        }

        public IActionResult ConfirmarDeletar(int id)
        {
            _orcamentoRepositorio.Apagar(id);
            return RedirectToAction("Index");
        }


        [HttpPost]
        public IActionResult Criar(OrcamentoViewModel viewModel)
        {
            UsuarioModel usuarioLogado = _sessao.BuscarSessaoUsuario();
            viewModel.Orcamento.UsuarioId = usuarioLogado.Id;

            var projetosSelecionados = _projetoRepositorio.BuscarTodos(usuarioLogado.Id)
                .Where(p => viewModel.ProjetosSelecionados.Contains(p.Id))
                .ToList();

            viewModel.Orcamento.Projetos = projetosSelecionados;

            _orcamentoRepositorio.Adicionar(viewModel.Orcamento);
            return RedirectToAction("Index");
        }


        [HttpPost]
        public IActionResult Editar(OrcamentoViewModel viewModel)
        {
            UsuarioModel usuarioLogado = _sessao.BuscarSessaoUsuario();
            viewModel.Orcamento.UsuarioId = usuarioLogado.Id;

            // Obtém os projetos selecionados
            var projetosSelecionados = _projetoRepositorio.BuscarTodos(usuarioLogado.Id)
                .Where(m => viewModel.ProjetosSelecionados.Contains(m.Id))
                .ToList();

            // Atualiza os dados do projeto
            viewModel.Orcamento.Projetos = projetosSelecionados;

            _orcamentoRepositorio.Editar(viewModel.Orcamento);
            TempData["MensagemSucesso"] = "Projeto editado com sucesso!";
            return RedirectToAction("Index");
        }

        public IActionResult GerarPDF(int id)
        {
            // Gerar os dados do PDF em memória
            var pdfData = _orcamentoService.GerarPdf(id);

            return new FileContentResult(pdfData, "application/pdf");
        }



    }
}

codigo-fonte/Views/Orcamento/Criar.cshtml
@model PUConstruir.ViewModels.OrcamentoViewModel

@{
    ViewBag.Title = "Criar";
}

<div class="modal-content">
    <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Criar Orcamento</h1>
    </div>
    <form asp-action="Criar">
        <div class="modal-body">
            <div data-mdb-input-init>
                <label>Nome:</label>
                <input asp-for="Orcamento.Nome" type="text" maxlength="120" class="form-outline mb-4 form-control form-control-lg form-projeto" id="nome" placeholder="Nome do orçamento">
                <span asp-validation-for="Orcamento.Nome" class="text-danger"></span>
            </div>

            <div data-mdb-input-init>
                <label>Projetos</label>
                <select asp-for="ProjetosSelecionados" class="form-control" multiple>
                    @foreach (var projeto in Model.TodosProjetos)
                    {
                        <option value="@projeto.Id">@projeto.NomeProjeto</option>
                    }
                </select>
            </div>

            <div class="modal-footer">
                <a asp-area="" asp-controller="Orcamento" asp-action="Index" class="btn btn-secondary">Voltar</a>
                <button type="submit" class="btn btn-primary">Cadastrar</button>
            </div>
        </div>
    </form>
</div>

codigo-fonte/Views/Orcamento/Deletar.cshtml
@model OrcamentoModel;

@{
    ViewBag.Title = "Deletar";
}

<div class="centralizarTela mt-5">
    <div class="telaDeletar modal-content">
        <div class="modal-header">
            <h4 class="modal-title" id="exampleModalLabel">Excluir orçamento</h4>
        </div>
        <div class="modal-body text-start">
            <p> 
                Você está prestes a excluir o orçamento <strong>@Model.Nome</strong>.<br>
                Esta é uma ação definitiva, sem possibilidade de reversão.<br><br>
                Tem certeza que deseja prosseguir?
            </p>
        </div>
        <div class="modal-footer">
            <a asp-controller="Orcamento" asp-action="Index" role="button" class="btn btn-secondary">Cancelar</a>
            <a type="button" asp-route-id="@Model.Id" asp-controller="Orcamento" asp-action="ConfirmarDeletar" class="btn btn-danger">Excluir</a>
        </div>
    </div>
</div>

codigo-fonte/Views/Orcamento/Editar.cshtml
@model PUConstruir.ViewModels.OrcamentoViewModel

@{
    ViewBag.Title = "Editar";
}

<div class="modal-content">
    <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Editar Orcamento</h1>
    </div>
    <form asp-action="Editar" method="post">

        <input type="hidden" asp-for="Orcamento.Id" />

        <div class="modal-body">
            <div data-mdb-input-init>
                <label>Nome:</label>
                <input asp-for="Orcamento.Nome" type="text" maxlength="120" class="form-outline mb-4 form-control form-control-lg form-projeto" id="nome" placeholder="Nome do orçamento">
                <span asp-validation-for="Orcamento.Nome" class="text-danger"></span>
            </div>

            <div data-mdb-input-init>
                <label>Projetos</label>
                <select asp-for="ProjetosSelecionados" class="form-control" multiple>
                    @foreach (var projeto in Model.TodosProjetos)
                    {
                        <option value="@projeto.Id">@projeto.NomeProjeto</option>
                    }
                </select>
            </div>

            <div class="modal-footer">
                <a asp-area="" asp-controller="Orcamento" asp-action="Index" class="btn btn-secondary">Voltar</a>
                <button type="submit" class="btn btn-primary">Editar</button>
            </div>
        </div>
    </form>
</div>

codigo-fonte/Views/Orcamento/Index.cshtml
@model List<OrcamentoModel>

@{
    ViewData["Title"] = "Orçamento";
}

<div id="ProjetosTitulo">
    <h1>@ViewData["Title"]</h1>
    <a asp-area="" asp-controller="Orcamento" asp-action="Criar" class="btn btn-dark btn-lg btn-block">
        Adicionar orçamento +
    </a>
</div>

@if (Model != null && Model.Any())
{
    foreach (OrcamentoModel orcamento in Model)
    {
        <div id="listaStl">
            <div class="NomeDoProjeto">
                <h5>@orcamento.Nome</h5>
            </div>
            <div class="BotaoLateral">
                <!-- Botao visualizar -->
                <a asp-route-id="@orcamento.Id" asp-area="" asp-controller="Orcamento" asp-action="Visualizar" type="button" class="btn btn-lg btn-block btnCrud">
                    <i class="fa-solid fa-magnifying-glass"></i>
                </a>
                <!-- Botao editar -->
                <a asp-route-id="@orcamento.Id" asp-area="" asp-controller="Orcamento" asp-action="Editar" type="button" class="btn btn-lg btn-block btnCrud">
                    <i class="fa-solid fa-pencil"></i>
                </a>
                <!-- Botao excluir -->
                <a asp-route-id="@orcamento.Id" asp-area="" asp-controller="Orcamento" asp-action="Deletar" type="button" class="btn btn-lg btn-block btnCrud">
                    <i class="fa-solid fa-trash-can"></i>
                </a>
                <!-- Gerar PDF -->
                <a asp-route-id="@orcamento.Id" asp-area="" asp-controller="Orcamento" asp-action="GerarPDF" target="_blank" type="button" class="btn btn-lg btn-block btnCrud">
                    <i class="fa-solid fa-file-pdf"></i>
                </a>
            </div>
        </div>
    }
}

codigo-fonte/Views/Orcamento/Visualizar.cshtml
@model PUConstruir.Models.OrcamentoModel;

@{
    ViewBag.Title = "Visualizar";
}

<div class="modal-content">
    <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Visualizar orçamento</h1>
        <a asp-area="" asp-controller="Orcamento" asp-action="GerarPDF" asp-route-id="@Model.Id" target="_blank" class="btn btn-dark">Gerar PDF</a>

    </div>
    <div class="modal-body">

        <div data-mdb-input-init>
            <label>Nome:</label>
            <input type="text" readonly maxlength="120" class="form-outline mb-4 form-control form-control-lg form-projeto" id="nome" placeholder="@Model.Nome">
        </div>

        <div data-mdb-input-init>
            <label>Valor Total:</label>
            <input type="number" readonly maxlength="18" min="0" step="0.01" class="form-outline mb-4 form-control form-control-lg form-projeto" id="valorTotal" placeholder="@Model.ValorTotal">
        </div>

        
        <div data-mdb-input-init>
            <label>Projetos:</label>
            @foreach (var projeto in Model.Projetos)
            {
                <div class="modal-content mb-4">
                    <input readonly maxlength="120" min="0" step="0.01" class="form-outline mb-4 form-control form-control-lg form-projeto" placeholder="@projeto.NomeProjeto" />
                    <ul style="list-style: none;">
                        <li>
                            <strong>Descrição:</strong> @projeto.Descricao <br />
                            <strong>Data Inicial:</strong> @projeto.DataInicial?.ToString("dd/MM/yyyy") <br />
                            <strong>Data Final:</strong> @projeto.DataFinal?.ToString("dd/MM/yyyy") <br />
                            <strong>Valor:</strong> @projeto.Valor.ToString("C") <br />
                            <strong>Materiais:</strong>
                            @if (projeto.Materiais != null)
                            {
                                <ul>
                                    @foreach (var material in projeto.Materiais)
                                    {
                                        <li>@material.Descricao</li>
                                    }
                                </ul>
                            }
                            else
                            {
                                <p>Nenhum material associado.</p>
                            }
                            <strong>Serviços:</strong>
                            @if (projeto.Servicos != null)
                            {
                                <ul>
                                    @foreach (var servico in projeto.Servicos)
                                    {
                                        <li>@servico.Descricao</li>
                                    }
                                </ul>
                            }
                            else
                            {
                                <p>Nenhum serviço associado.</p>
                            }
                        </li>
                    </ul>
                </div>
             }
        </div>
    </div>

    <div class="modal-footer">
        <a asp-area="" asp-controller="Orcamento" asp-action="Index" class="btn btn-dark">Voltar</a>
    </div>
</div>