codigo-fonte/Controllers/IndexController.cs
using Microsoft.AspNetCore.Mvc;
using PUConstruir.Filters;

namespace PUConstruir.Controllers
{
    public class IndexController : Controller
    {
        [UsuarioLogado]
        public IActionResult Index()
        {
            return View();
        }

    }
}

codigo-fonte/Controllers/ProjetoController.cs
using Microsoft.AspNetCore.Mvc;
using PUConstruir.Filters;
using PUConstruir.Helper;
using PUConstruir.Models;
using PUConstruir.Repositorio;
using PUConstruir.ViewModels;


namespace PUConstruir.Controllers
{
    [UsuarioLogado]
    public class ProjetoController : Controller
    {
        private readonly IProjetoRepositorio _projetoRepositorio;
        private readonly IMaterialRepositorio _materialRepositorio;
        private readonly IServicoRepositorio _servicoRepositorio;
        private readonly ISessao _sessao;

        public ProjetoController(IProjetoRepositorio projetoRepositorio, ISessao sessao, IMaterialRepositorio materialRepositorio, IServicoRepositorio servicoRepositorio)
        {
            _projetoRepositorio = projetoRepositorio;
            _materialRepositorio = materialRepositorio;
            _servicoRepositorio = servicoRepositorio;
            _sessao = sessao;
        }

        public IActionResult Index()
        {
            UsuarioModel usuarioLogado = _sessao.BuscarSessaoUsuario();
            List<ProjetoModel> projetos = _projetoRepositorio.BuscarTodos(usuarioLogado.Id);
            return View(projetos);
        }

        public IActionResult Criar()
        {
            UsuarioModel usuarioLogado = _sessao.BuscarSessaoUsuario();
            var viewModel = new ProjetoViewModel
            {
                TodosMateriais = _materialRepositorio.BuscarTodos(usuarioLogado.Id),
                TodosServicos = _servicoRepositorio.BuscarTodos(usuarioLogado.Id)
            };
            return View(viewModel);
        }

        public IActionResult Visualizar(int id)
        {
            ProjetoModel projeto = _projetoRepositorio.BuscarPorId(id);
            return View(projeto);
        }

        public IActionResult Editar(int id)
        {
            UsuarioModel usuarioLogado = _sessao.BuscarSessaoUsuario();
            ProjetoModel projeto = _projetoRepositorio.BuscarPorId(id);
            var viewModel = new ProjetoViewModel
            {
                Projeto = projeto,
                TodosMateriais = _materialRepositorio.BuscarTodos(usuarioLogado.Id),
                TodosServicos = _servicoRepositorio.BuscarTodos(usuarioLogado.Id),
                MateriaisSelecionados = projeto.Materiais.Select(m => m.Id).ToList(),
                ServicosSelecionados = projeto.Servicos.Select(s => s.Id).ToList()
            };
            return View(viewModel);
        }

        public IActionResult Deletar(int id)
        {
            ProjetoModel projeto = _projetoRepositorio.BuscarPorId(id);
            return View(projeto);
        }

        public IActionResult ConfirmarDeletar(int id)
        {
            _projetoRepositorio.Apagar(id);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Criar(ProjetoViewModel viewModel)
        {
            UsuarioModel usuarioLogado = _sessao.BuscarSessaoUsuario();
            viewModel.Projeto.UsuarioId = usuarioLogado.Id;

            // Obtém os materiais selecionados
            var materiaisSelecionados = _materialRepositorio.BuscarTodos(usuarioLogado.Id)
                .Where(m => viewModel.MateriaisSelecionados.Contains(m.Id))
                .ToList();

            // Obtém os serviços selecionados
            var servicosSelecionados = _servicoRepositorio.BuscarTodos(usuarioLogado.Id)
                .Where(s => viewModel.ServicosSelecionados.Contains(s.Id))
                .ToList();

            // Adiciona os materiais ao projeto
            viewModel.Projeto.Materiais = materiaisSelecionados;
            viewModel.Projeto.Servicos = servicosSelecionados;

            _projetoRepositorio.Adicionar(viewModel.Projeto);
            TempData["MensagemSucesso"] = "Projeto cadastrado com sucesso!";
            return RedirectToAction("Index");
        }


        [HttpPost]
        public IActionResult Editar(ProjetoViewModel viewModel)
        {
            UsuarioModel usuarioLogado = _sessao.BuscarSessaoUsuario();
            viewModel.Projeto.UsuarioId = usuarioLogado.Id;

            // Obtém os materiais selecionados
            var materiaisSelecionados = _materialRepositorio.BuscarTodos(usuarioLogado.Id)
                .Where(m => viewModel.MateriaisSelecionados.Contains(m.Id))
                .ToList();

            // Obtém os serviços selecionados
            var servicosSelecionados = _servicoRepositorio.BuscarTodos(usuarioLogado.Id)
                .Where(s => viewModel.ServicosSelecionados.Contains(s.Id))
                .ToList();

            // Atualiza os dados do projeto
            viewModel.Projeto.Materiais = materiaisSelecionados;
            viewModel.Projeto.Servicos = servicosSelecionados;

            _projetoRepositorio.Editar(viewModel.Projeto);
            TempData["MensagemSucesso"] = "Projeto editado com sucesso!";
            return RedirectToAction("Index");
        }
    }
}

codigo-fonte/Controllers/ServicoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PUConstruir.Data;
using PUConstruir.Filters;
using PUConstruir.Helper;
using PUConstruir.Models;
using PUConstruir.Repositorio;

namespace PUConstruir.Controllers
{
    [UsuarioLogado]
    public class ServicoController : Controller
    {
        private readonly IServicoRepositorio _servicoRepositorio;

        private readonly ISessao _sessao;

        public ServicoController(IServicoRepositorio servicoRepositorio, ISessao sessao)
        {
            _servicoRepositorio = servicoRepositorio;
            _sessao = sessao;
        }

        //OK
        public IActionResult Index()
        {
            UsuarioModel usuarioLogado = _sessao.BuscarSessaoUsuario();
            List<ServicoModel> servicos = _servicoRepositorio.BuscarTodos(usuarioLogado.Id);
            return View(servicos);
        }

        //OK
        public IActionResult Criar()
        {
            return View();
        }

        //OK
        public IActionResult Deletar(int id)
        {
            ServicoModel servico = _servicoRepositorio.BuscarPorId(id);
            return View(servico);
        }
        public IActionResult ConfirmarDeletar(int id)
        {
            _servicoRepositorio.Deletar(id);
            return RedirectToAction("Index");
        }

        //OK
        public IActionResult Editar(int id)
        {
            ServicoModel servico = _servicoRepositorio.BuscarPorId(id);
            return View(servico);
        }

        //OK
        public IActionResult Visualizar(int id)
        {
            ServicoModel servico = _servicoRepositorio.BuscarPorId(id);
            return View(servico);
        }



        [HttpPost]
        public IActionResult Criar(ServicoModel servico)
        {
            UsuarioModel usuarioLogado = _sessao.BuscarSessaoUsuario();
            servico.UsuarioId = usuarioLogado.Id;
            _servicoRepositorio.Criar(servico);
            TempData["MensagemSucesso"] = "Serviço cadastrado com sucesso!";
            return RedirectToAction("Index");
        }


        [HttpPost]
        public IActionResult Editar(ServicoModel servico)
        {
            UsuarioModel usuarioLogado = _sessao.BuscarSessaoUsuario();
            servico.UsuarioId = usuarioLogado.Id;
            _servicoRepositorio.Editar(servico);
            TempData["MensagemSucesso"] = "Serviço editado com sucesso!";
            return RedirectToAction("Index");
        }
    }
}

codigo-fonte/Controllers/UsuarioController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PUConstruir.Filters;
using PUConstruir.Helper;
using PUConstruir.Models;
using PUConstruir.Repositorio;
using PUConstruir.ViewModels;
using System.Linq.Expressions;

namespace PUConstruir.Controllers
{
    public class UsuarioController : Controller
    {
        private readonly IUsuarioRepositorio _usuarioRepositorio;
        private readonly ISessao _sessao;

        public UsuarioController(IUsuarioRepositorio usuarioRepositorio, ISessao sessao)
        {
            _usuarioRepositorio = usuarioRepositorio;
            _sessao = sessao;
        }

        public IActionResult Criar()
        {
            return View();
        }

        [UsuarioLogado]
        public IActionResult Perfil(int id) 
        {
            UsuarioModel usuarioLogado = _sessao.BuscarSessaoUsuario();
            UsuarioModel usuario = _usuarioRepositorio.BuscarPorId(usuarioLogado.Id);
            return View(usuario);
        }

        [UsuarioLogado]
        public IActionResult AlterarSenha()
        {
            return View();
        }

        public IActionResult Deletar(int id)
        {
            UsuarioModel usuarioLogado = _sessao.BuscarSessaoUsuario();
            UsuarioModel usuario = _usuarioRepositorio.BuscarPorId(usuarioLogado.Id);
            return View(usuario);
        }

        public IActionResult ConfirmarDeletar(int id)
        {
            try
            {
                _usuarioRepositorio.Apagar(id);

                TempData["MensagemSucesso"] = "Conta excluída com sucesso!";
                _sessao.RemoverSessaoUsuario();
                return RedirectToAction("Index", "Login");
            }
            catch (Exception ex)
            {
                TempData["MensagemErro"] = $"Erro ao excluir a conta: {ex.Message}";
                return RedirectToAction("Perfil");
            }
        }

        [HttpPost]
        public IActionResult Criar(UsuarioModel usuario)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    usuario = _usuarioRepositorio.Adicionar(usuario);
                    TempData["MensagemSuccesso"] = "Usuário cadastrado com sucesso!";
                    _sessao.CriarSessaoUsuario(usuario);
                    return RedirectToAction("Index", "Index");
                }
                return View(usuario);
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos cadastrar seu usuário, tente novamente.";
                return RedirectToAction("Login", "Index");
            }
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [UsuarioLogado]
        public IActionResult AlterarSenha(AlterarSenhaViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    UsuarioModel usuario = _sessao.BuscarSessaoUsuario();
                    UsuarioModel usuarioDB = _usuarioRepositorio.BuscarPorId(usuario.Id);

                    if (usuarioDB == null)
                        throw new Exception("Usuário não encontrado!");

                    usuarioDB.Senha = model.NovaSenha.gerarHash();
                    _usuarioRepositorio.Editar(usuarioDB);

                    TempData["MensagemSucesso"] = "Senha alterada com sucesso!";
                    return RedirectToAction("Perfil");
                }
                catch (Exception ex)
                {
                    TempData["MensagemErro"] = $"Erro ao alterar a senha: {ex.Message}";
                }
            }
            return View(model);
        }
    }
}

codigo-fonte/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PUConstruir</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PUConstruir.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Index" asp-action="Index">PUConstruir</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Material" asp-action="Index">Materiais</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Servico" asp-action="Index">Serviços</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Projeto" asp-action="Index">Projetos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Orcamento" asp-action="Index">Orçamentos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Perfil">Perfil</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Deslogar">Deslogar</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - PUConstruir
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://kit.fontawesome.com/611cc71e79.js" crossorigin="anonymous"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

codigo-fonte/Views/Shared/_LayoutDeslogado.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PUConstruir</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PUConstruir.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Index" asp-action="Index">PUConstruir</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - PUConstruir
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://kit.fontawesome.com/611cc71e79.js" crossorigin="anonymous"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>